export const PROPERTY_TYPES = [
  {
    id: "single-house",
    title: "Single House Property",
    icon: "Home",
    description: "Single unit house for single family",
    disabled: true,
  },
  {
    id: "apartments",
    title: "Apartments Complex",
    icon: "Building",
    description: "Multiple unit house for families",
    disabled: true,
  },
  {
    id: "condominiums",
    title: "Condominiums",
    icon: "Building2",
    description: "Multiple unit house for families",
    disabled: false,
  },
];

export const USER_ROLES = [
  {
    id: "landlord",
    title: "Landlord",
    description: "Owner of the property",
    icon: "KeySquare",
  },
  {
    id: "realtor",
    title: "Realtor",
    description: "Manage property on behalf on owner",
    icon: "User",
  },
  {
    id: "property-management",
    title: "Property Management Company",
    description: "For management company",
    icon: "Building",
  },
];

export const PLANS = [
  {
    id: "regular",
    name: "Regular",
    price: 99.99,
    features: ["Price for 1-50 units"],
  },
  {
    id: "platinum",
    name: "Platinum",
    price: 129.99,
    features: ["Price for 1-50 units"],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 199.99,
    features: ["Price for 1-50 units"],
  },
];

export const PET_TYPES = ["Dog", "Cat", "Bird", "Fish", "Rabbit", "Other"];

export const UTILITY_TYPES = [
  "Electricity",
  "Gas",
  "Water",
  "Internet",
  "Cable",
  "Trash",
  "Sewer",
];

export const AMENITIES = [
  "Air conditioning",
  "Cable ready",
  "Ceiling fan",
  "High ceilings",
  "Private balcony",
  "Refrigerator",
  "Wooded views",
  "W/D hookup",
  "Hardwood Floor",
  "Fireplace",
  "First aid kit",
  "Carbon monoxide alarm",
  "Expanded patios",
  "Free parking on premises",
  "Fire extinguisher",
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
